import s from './home.module.scss'
import Divider from '../../components/Divider'
import Tabs from '../../components/Tabs'
import Banner from './Banner'
import Banner2 from './Banner2'

const Home = () => {

    return (
        <div className={s.container}>
            <Banner>
                <div className={s.bannerContent}>
                    <div className={s.bannerHeader}>
                        Making each stop <u>count</u>.
                    </div>
                    <div className={s.bannerText}>
                        This is the official website of <span>Waypoint</span>, a part of the Arangkadata project by the University of the Philippines – Diliman, funded by the Department of Science and Technology, and supported by the Department of Transportation.
                    </div>
                </div>
            </Banner>
            <Divider fill="#62A2CC" />
            <Banner2>
                <div className={s.banner2Content}>
                    <div className={s.banner2Header}>
                        The Website
                    </div>
                    <div className={s.banner2Text}>
                        In this website, we will be providing data regarding passenger traffic. This data includes where the stops are, how many people in average are seen at each stop, and how many of them alight and board at these stops. The data being provided is generated by a combination of a Computer-Vision algorithm and our own semi-automated annotation system. This annotation system utilizes the required onboard electronic devices in modern public-utility-vehicles (PUVs) to help human annotators in trimming down the amount of footage needed to be reviewed to generate the data that the site provides. Waypoint’s aim is to help all in the transportation sector as well as those who utilize their services in improving the current transportation environment in the country.
                    </div>
                    <Tabs className={s.tabs}>
                        {[
                            <div id="Map" key="map" className={s.tabContent}>
                                The map page aims to display vehicle occupancy data with a map reference. In line with this, our map contains a route selection and map interface. A data filter is also available to sort viewed data. Circles displayed on the map represent the number corresponding to the selected data. The values of the circles are averaged and summarized with respect to the vicinity.
                            </div>,
                            <div id="Annotation" key="annotation" className={s.tabContent}>
                                The annotation page is meant for annotators to interact and review videos that have been processed by the system. Once an annotator has received his/her code, logging in with the code will make the annotation page available. In the annotation page we'll find the videos and a form to answer in evaluating each video.
                            </div>
                        ]}
                    </Tabs>
                </div>
            </Banner2>
        </div>
    )
}

export default Home